<?php

/**
 * @file
 * Contains contacts.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function contacts_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the contacts module.
    case 'help.page.contacts':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Number, address') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function contacts_theme() {
  return [
    'contacts' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_theme().
 */
function contacts_theme() {
  $theme = [];
  $theme['contactss_entity'] = [
    'render element' => 'elements',
    'file' => 'contactss_entity.page.inc',
    'template' => 'contactss_entity',
  ];
  $theme['contactss_entity_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'contactss_entity.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function contacts_theme_suggestions_contactss_entity(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#contactss_entity'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'contactss_entity__' . $sanitized_view_mode;
  $suggestions[] = 'contactss_entity__' . $entity->bundle();
  $suggestions[] = 'contactss_entity__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'contactss_entity__' . $entity->id();
  $suggestions[] = 'contactss_entity__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
